add hero profile frontend
backmeupplz/todorant-frontend pull request #5
Opened 2020-06-28 20:16 UTC by upacyxou

![image](https://user-images.githubusercontent.com/57546893/85957321-701a5780-b99d-11ea-83b1-200404ad4687.png) mobile light
![image](https://user-images.githubusercontent.com/57546893/85957333-832d2780-b99d-11ea-9134-7342e05d981c.png) pc light
![image](https://user-images.githubusercontent.com/57546893/85957356-af48a880-b99d-11ea-9f46-9532db8287d6.png) mobile dark
![image](https://user-images.githubusercontent.com/57546893/85957358-bcfe2e00-b99d-11ea-89e6-45713ef17ae6.png) pc dark

2020-06-29 19:29 UTC, backmeupplz commented
* Поинты нужно начислять и при создании уже завершенных задач
* Попробуй тут сверстать дизайн, [как тут](https://www.figma.com/file/BCka0nxnc2k67hclHIYiw4/Untitled?node-id=0%3A1). Заметь, что тут есть прогресс-бары. Прикладываю реализацию на мобильных в качестве референса.
* Сделай цвета, как на мобилке, тоже прикладываю реализацию схем цветов.

[sharedColors.ts.zip](https://github.com/backmeupplz/todorant-frontend/files/4847625/sharedColors.ts.zip)
[hero.zip](https://github.com/backmeupplz/todorant-frontend/files/4847627/hero.zip)

2020-06-29 19:30 UTC, backmeupplz requested changes

2020-06-29 19:30 UTC, backmeupplz commented on src/assets/localization.ts
> +    nextRank: '{points} очков до следующего уровня',
Попробуй использовать уже существующие строки

2020-06-29 19:30 UTC, backmeupplz commented on src/components/CurrentTodo.vue
>        await api.completeTodo(user, this.todo)
Вот этот метод на сервере должен автоматически увеличивать очки.

2020-06-29 19:30 UTC, backmeupplz commented on src/components/TodoList.vue
>          await api.completeTodo(user, todo)
Тут тоже сам метод должен на сервере инкрементировать все автоматически.

2020-06-29 19:30 UTC, backmeupplz commented on src/utils/api.ts
> +export async function getHeroPoints(user: User) {
Технически, этих трех методов быть не должно.

2020-07-05 22:52 UTC, upacyxou commented
![image](https://user-images.githubusercontent.com/57546893/86543869-87c08580-bf33-11ea-8046-8f7790b8cc11.png)
![image](https://user-images.githubusercontent.com/57546893/86543879-9444de00-bf33-11ea-9397-8a4f422e02c4.png)
![image](https://user-images.githubusercontent.com/57546893/86543893-a6268100-bf33-11ea-8cdd-6849c1c0aaaf.png)
![image](https://user-images.githubusercontent.com/57546893/86543898-acb4f880-bf33-11ea-8502-cbe000178ee1.png)

2020-07-06 14:51 UTC, backmeupplz requested changes

2020-07-06 14:51 UTC, backmeupplz commented on src/components/HeroProfile.vue
> +      div.d-flex.ma-2
Вместо `div.d-flex.ma-2` можно писать просто `.d-flex.ma-2`. Pug автодополнит `div`. Поправь везде.

2020-07-08 18:38 UTC, closed without merging